# Python Lists

## Creating

In [329]:
# this is a python list
a = [42, 7, 13, 24601, 2001, 3.50]

In [330]:
# this is a list comprehension -- think of it as a sexy for loop

# the following gives us a list in which we multiplied each element in a by 2
z = [i * 2 for i in a]
z

[84, 14, 26, 49202, 4002, 7.0]

## Indexing

In [331]:
# you can index into it
a[0]

42

In [332]:
# what's the 3rd element?
a[3]

24601

In [333]:
# indices can also be negative
# this gives you the last element
a[-1]

3.5

## Slicing

In [334]:
# you can also get subsets of the list with slicing
#     a[start:end]
# [start, end)

# this returns the 3rd and 4th entries (indices 2 and 3 -- note we exclude 4!)
a[2:4]

[13, 24601]

In [335]:
# if you leave one side blank, it automatically goes all the way
# first five:
a[:5]

[42, 7, 13, 24601, 2001]

In [336]:
# how do you get the last three elements?
a[-3:]

[24601, 2001, 3.5]

In [337]:
# slices can also skip numbers
# a[start:end:interval]

# this gives us every other number, starting with the first
a[::2]

[42, 13, 2001]

In [338]:
# the interval can also be negative
# what does that do?

a[::-2]

[3.5, 24601, 7]

# Numpy

In [339]:
import numpy as np

## Creating

In [340]:
# numpy arrays can be created from a python list
b = np.array(a)
b

array([4.2000e+01, 7.0000e+00, 1.3000e+01, 2.4601e+04, 2.0010e+03,
       3.5000e+00])

Right now, it looks an awful like a python list, but there are some key points you should know.

numpy arrays are:
- homogeneous (all elements in an array have the same type)
- multidimensional

In [341]:
# Homogeneous: all numpy arrays have an associated data type.
# numbers are usually ints or floats
b.dtype

dtype('float64')

In [342]:
# Multidimensional: numpy arrays can have multiple dimensions, like a nested list.
# We can reshape b into a 3x2 matrix
# Note: this doesn't change b. That's why we assign it to a new variable: m
m = b.reshape(3, 2)
m

array([[4.2000e+01, 7.0000e+00],
       [1.3000e+01, 2.4601e+04],
       [2.0010e+03, 3.5000e+00]])

In [343]:
# Each dimension is called an axis
# The size across each axis is called the shape
# These are two very important concepts!
m.shape

(3, 2)

## Indexing

In [344]:
# We index into numpy arrays much the same way as python lists.
b[0]

42.0

In [345]:
# But N-dimensional arrays mean we can be more expressive with indexing
# This gives us [0th index of axis 0, 1st index of axis 1]
# You can think of this as a grid
# Alternatively, this is like m[0][1]
m[0, 1]

7.0

In [346]:
# We can also pass in multiple indices as a list
# This gives us the 1st, 2nd, and 5th values of b
b[[0, 1, 4]]

array([  42.,    7., 2001.])

In [347]:
# Let's combine these two facts to get the 2nd and 3rd items in the second column of m
m[[1, 2], 1]

array([2.4601e+04, 3.5000e+00])

In [348]:
# We can also incorporate our previous knowledge of slices.
# So to get the second column
# This gives us the entire range on axis 0, and only the 1st index on axis 1
m[:,1]

array([7.0000e+00, 2.4601e+04, 3.5000e+00])

## Math

In [349]:
# numpy gives us a lot of math functions to work with
# I'll only show you a couple, but you can find them all in the documentation

np.sum(b)  # guess what this does?

26667.5

In [350]:
np.mean(b)  # and this?

4444.583333333333

In [351]:
# for convenience, you can also call
b.mean()

4444.583333333333

In [352]:
# you can also apply these functions to only one axis
# only sum across rows (read: apply the sum to axis 1)
np.sum(m, axis=1)

array([   49. , 24614. ,  2004.5])

In [353]:
# numpy has a concept called podcasting
# It tries to coerce non-matching shapes.
# 2 is a scalar, but we can still multiply m by it
# it just repeats the 2 across all instances of m
m * 2

array([[8.4000e+01, 1.4000e+01],
       [2.6000e+01, 4.9202e+04],
       [4.0020e+03, 7.0000e+00]])

# Pandas

In [354]:
import pandas as pd

## Creating

Pandas lets us read all sorts of data into a Dataframe. Think of this as a series of lists. Let's look at an example.

In [355]:
df = pd.read_csv("./cereal.csv")
type(df)

pandas.core.frame.DataFrame

In [356]:
# head() gives us the first 10 rows in the dataframe (pd.DataFrame)
df.head()

name mfr type  calories  protein  fat  sodium  fiber  \
0                  100% Bran   N    C        70        4    1     130   10.0   
1          100% Natural Bran   Q    C       120        3    5      15    2.0   
2                   All-Bran   K    C        70        4    1     260    9.0   
3  All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   
4             Almond Delight   R    C       110        2    2     200    1.0   

   carbo  sugars  potass  vitamins  shelf  weight  cups     rating  
0    5.0       6     280        25      3     1.0  0.33  68.402973  
1    8.0       8     135         0      3     1.0  1.00  33.983679  
2    7.0       5     320        25      3     1.0  0.33  59.425505  
3    8.0       0     330        25      3     1.0  0.50  93.704912  
4   14.0       8      -1        25      3     1.0  0.75  34.384843

In [357]:
# you can think of each column as a list (or a 1D numpy array)
# in practice, these are called pandas Series (pd.Series)
# you can index into the dataframe with a string to get one column
df["name"]

0                     100% Bran
1             100% Natural Bran
2                      All-Bran
3     All-Bran with Extra Fiber
4                Almond Delight
                ...            
72                      Triples
73                         Trix
74                   Wheat Chex
75                     Wheaties
76          Wheaties Honey Gold
Name: name, Length: 77, dtype: object

In [358]:
type(df["name"])

pandas.core.series.Series

## Pandas Series vs Numpy Arrays

In [359]:
# There are many similarities between pd.Series and np.ndarray
# for example:
df["carbo"].mean()

14.597402597402597

In [360]:
# In fact, we can turn pd.Series into a numpy array
# again, this returns a numpy array -- df["carbo"] doesn't change.
df["carbo"].to_numpy()

array([ 5. ,  8. ,  7. ,  8. , 14. , 10.5, 11. , 18. , 15. , 13. , 12. ,
       17. , 13. , 13. , 12. , 22. , 21. , 13. , 12. , 10. , 21. , 21. ,
       11. , 18. , 11. , 14. , 14. , 12. , 14. , 13. , 11. , 15. , 15. ,
       17. , 13. , 12. , 11.5, 14. , 17. , 20. , 21. , 12. , 12. , 16. ,
       16. , 16. , 17. , 15. , 15. , 21. , 18. , 13.5, 11. , 20. , 13. ,
       10. , 14. , -1. , 14. , 10.5, 15. , 23. , 22. , 16. , 19. , 20. ,
        9. , 16. , 15. , 21. , 15. , 16. , 21. , 13. , 17. , 17. , 16. ])

In [361]:
# The key difference is that Series are indexed
# See the 0, 1, ... 76 on the left? That is the index of each item.
# Right now they are just positions, but theoretically they can be any unique identifier for the row
# Think: ID, username, etc
df["carbo"].index

RangeIndex(start=0, stop=77, step=1)

## Indexing into DataFrames and Series

In [362]:
# Indexing is a little bit different in pandas.
# One parallel to what you've been used to is .loc[]
# this is the row at index 0
df.loc[0]

name        100% Bran
mfr                 N
type                C
calories           70
protein             4
fat                 1
sodium            130
fiber              10
carbo               5
sugars              6
potass            280
vitamins           25
shelf               3
weight              1
cups             0.33
rating         68.403
Name: 0, dtype: object

In [363]:
# multiple indices work
df.loc[[1, 2, 3]]

name mfr type  calories  protein  fat  sodium  fiber  \
1          100% Natural Bran   Q    C       120        3    5      15    2.0   
2                   All-Bran   K    C        70        4    1     260    9.0   
3  All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   

   carbo  sugars  potass  vitamins  shelf  weight  cups     rating  
1    8.0       8     135         0      3     1.0  1.00  33.983679  
2    7.0       5     320        25      3     1.0  0.33  59.425505  
3    8.0       0     330        25      3     1.0  0.50  93.704912

In [364]:
# caveat: remember that pandas doesn't require zero-indexing. indices can be anything.
# this means slicing might not work all the time (what would df.loc["asdf":"hjkl"] even mean?)
# in the cases that you actually want to index by row number, you can always do that with .iloc[]
# again, this will behave the same as .loc[] with our dataset because our data is 0-indexed
df.iloc[0]

name        100% Bran
mfr                 N
type                C
calories           70
protein             4
fat                 1
sodium            130
fiber              10
carbo               5
sugars              6
potass            280
vitamins           25
shelf               3
weight              1
cups             0.33
rating         68.403
Name: 0, dtype: object

In [365]:
# We can also use boolean indexing by passing a list of booleans like so:
df[[True] + [False] * 76]
# Let me explain:
# - [True] + [False] * 76 gives us a list that looks like [True, False, ..., False] with 1 True and 76 Falses
# - This matches the number of rows in our data (77)
# - pandas returns all the rows with a corresponding True (in this case, only the first one)

name mfr type  calories  protein  fat  sodium  fiber  carbo  sugars  \
0  100% Bran   N    C        70        4    1     130   10.0    5.0       6   

   potass  vitamins  shelf  weight  cups     rating  
0     280        25      3     1.0  0.33  68.402973

In [366]:
# This is powerful because we can also make comparisons with Series and values.
df["protein"] > 3

0      True
1     False
2      True
3      True
4     False
      ...  
72    False
73    False
74    False
75    False
76    False
Name: protein, Length: 77, dtype: bool

In [367]:
# Combining these two things, we have a very expressive way of filtering.
# This gives us all the rows in which the protein is greater than 3.
df[df["protein"] > 3]

name mfr type  calories  protein  fat  \
0                           100% Bran   N    C        70        4    1   
2                            All-Bran   K    C        70        4    1   
3           All-Bran with Extra Fiber   K    C        50        4    0   
11                           Cheerios   G    C       110        6    2   
41                               Life   Q    C       100        4    2   
43                              Maypo   A    H       100        4    1   
44   Muesli Raisins; Dates; & Almonds   R    C       150        4    3   
45  Muesli Raisins; Peaches; & Pecans   R    C       150        4    3   
56                 Quaker Oat Squares   Q    C       100        4    1   
57                     Quaker Oatmeal   Q    H       100        5    2   
67                          Special K   K    C       110        6    0   

    sodium  fiber  carbo  sugars  potass  vitamins  shelf  weight  cups  \
0      130   10.0    5.0       6     280        25      3     1.0  0.33   
2      260    9.0    7.0       5     320        25      3     1.0  0.33   
3      140   14.0    8.0       0     330        25      3     1.0  0.50   
11     290    2.0   17.0       1     105        25      1     1.0  1.25   
41     150    2.0   12.0       6      95        25      2     1.0  0.67   
43       0    0.0   16.0       3      95        25      2     1.0  1.00   
44      95    3.0   16.0      11     170        25      3     1.0  1.00   
45     150    3.0   16.0      11     170        25      3     1.0  1.00   
56     135    2.0   14.0       6     110        25      3     1.0  0.50   
57       0    2.7   -1.0      -1     110         0      1     1.0  0.67   
67     230    1.0   16.0       3      55        25      1     1.0  1.00   

       rating  
0   68.402973  
2   59.425505  
3   93.704912  
11  50.764999  
41  45.328074  
43  54.850917  
44  37.136863  
45  34.139765  
56  49.511874  
57  50.828392  
67  53.131324

## Manipulating Series

Often when we're preprocessing data, we want to make uniform changes to a specific column. We can do this by applying functions.

In [368]:
# Suppose we want to make the cereals more appetizing.
# Let's add "Delicious " to the beginning of every name.

# The pattern is we define a function for a single entry
def make_delicious(name):
    return "Delicious " + name

# and then call apply on the series to apply the function to each element in the series
df["name"].apply(make_delicious)

0                     Delicious 100% Bran
1             Delicious 100% Natural Bran
2                      Delicious All-Bran
3     Delicious All-Bran with Extra Fiber
4                Delicious Almond Delight
                     ...                 
72                      Delicious Triples
73                         Delicious Trix
74                   Delicious Wheat Chex
75                     Delicious Wheaties
76          Delicious Wheaties Honey Gold
Name: name, Length: 77, dtype: object

In [369]:
# this returns the changes, but doesn't apply them in place.
# that means on our original dataframe, the cereals are still bland
df.head()

name mfr type  calories  protein  fat  sodium  fiber  \
0                  100% Bran   N    C        70        4    1     130   10.0   
1          100% Natural Bran   Q    C       120        3    5      15    2.0   
2                   All-Bran   K    C        70        4    1     260    9.0   
3  All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   
4             Almond Delight   R    C       110        2    2     200    1.0   

   carbo  sugars  potass  vitamins  shelf  weight  cups     rating  
0    5.0       6     280        25      3     1.0  0.33  68.402973  
1    8.0       8     135         0      3     1.0  1.00  33.983679  
2    7.0       5     320        25      3     1.0  0.33  59.425505  
3    8.0       0     330        25      3     1.0  0.50  93.704912  
4   14.0       8      -1        25      3     1.0  0.75  34.384843

In [370]:
# we can fix this by assigning the new names to the column.
df["name"] = df["name"].apply(make_delicious)
df.head()

name mfr type  calories  protein  fat  \
0                  Delicious 100% Bran   N    C        70        4    1   
1          Delicious 100% Natural Bran   Q    C       120        3    5   
2                   Delicious All-Bran   K    C        70        4    1   
3  Delicious All-Bran with Extra Fiber   K    C        50        4    0   
4             Delicious Almond Delight   R    C       110        2    2   

   sodium  fiber  carbo  sugars  potass  vitamins  shelf  weight  cups  \
0     130   10.0    5.0       6     280        25      3     1.0  0.33   
1      15    2.0    8.0       8     135         0      3     1.0  1.00   
2     260    9.0    7.0       5     320        25      3     1.0  0.33   
3     140   14.0    8.0       0     330        25      3     1.0  0.50   
4     200    1.0   14.0       8      -1        25      3     1.0  0.75   

      rating  
0  68.402973  
1  33.983679  
2  59.425505  
3  93.704912  
4  34.384843

In [371]:
# here's another example.
# Jackson is a skeptic and doesn't believe calling things "Delicious" makes them taste better.
# But he does think adding sugar will make them taste better.
# How can we add 10 grams of sugar to every cereal?
df["sugars"] = df["sugars"].apply(lambda s : s + 10)
df

name mfr type  calories  protein  fat  \
0                   Delicious 100% Bran   N    C        70        4    1   
1           Delicious 100% Natural Bran   Q    C       120        3    5   
2                    Delicious All-Bran   K    C        70        4    1   
3   Delicious All-Bran with Extra Fiber   K    C        50        4    0   
4              Delicious Almond Delight   R    C       110        2    2   
..                                  ...  ..  ...       ...      ...  ...   
72                    Delicious Triples   G    C       110        2    1   
73                       Delicious Trix   G    C       110        1    1   
74                 Delicious Wheat Chex   R    C       100        3    1   
75                   Delicious Wheaties   G    C       100        3    1   
76        Delicious Wheaties Honey Gold   G    C       110        2    1   

    sodium  fiber  carbo  sugars  potass  vitamins  shelf  weight  cups  \
0      130   10.0    5.0      16     280        25      3     1.0  0.33   
1       15    2.0    8.0      18     135         0      3     1.0  1.00   
2      260    9.0    7.0      15     320        25      3     1.0  0.33   
3      140   14.0    8.0      10     330        25      3     1.0  0.50   
4      200    1.0   14.0      18      -1        25      3     1.0  0.75   
..     ...    ...    ...     ...     ...       ...    ...     ...   ...   
72     250    0.0   21.0      13      60        25      3     1.0  0.75   
73     140    0.0   13.0      22      25        25      2     1.0  1.00   
74     230    3.0   17.0      13     115        25      1     1.0  0.67   
75     200    3.0   17.0      13     110        25      1     1.0  1.00   
76     200    1.0   16.0      18      60        25      1     1.0  0.75   

       rating  
0   68.402973  
1   33.983679  
2   59.425505  
3   93.704912  
4   34.384843  
..        ...  
72  39.106174  
73  27.753301  
74  49.787445  
75  51.592193  
76  36.187559  

[77 rows x 16 columns]

## Groups and Aggregates

When we have lots and lots of data, it's more useful to look at aggregate statistics like the mean or median. But sometimes we lose too much detail aggregating across the whole dataset.

The solution is to aggregate across groups. For example, maybe we're less interested in the mean calorie count of all cereals and more interested in the mean for each manufacturer.

In [372]:
# First, we can see how many (and which) unique manufacturers there are
# Note: this gives us a numpy array
df["mfr"].unique()

array(['N', 'Q', 'K', 'R', 'G', 'P', 'A'], dtype=object)

In [373]:
# Now let's group by the manufacturers
# This gives us a groupby object across the dataframe
mfrs = df.groupby("mfr")
mfrs

In [374]:
# what happens if we try to access the calories column?
mfrs["calories"]

In [375]:
# now let's try to get the mean
mfrs["calories"].mean()

mfr
A    100.000000
G    111.363636
K    108.695652
N     86.666667
P    108.888889
Q     95.000000
R    115.000000
Name: calories, dtype: float64

In [376]:
# we can also aggregate across multiple columns, and even use different aggregations
# let's get the average calorie count but the maximum protein
mfrs[["calories", "protein"]].agg({"calories": "mean", "protein": "max"})

calories  protein
mfr                     
A    100.000000        4
G    111.363636        6
K    108.695652        6
N     86.666667        4
P    108.888889        3
Q     95.000000        5
R    115.000000        4

# Exercises

Unless otherwise noted, these should be one line of code.

In [377]:
# here is a Python list:

a = [1, 2, 3, 4, 5, 6]

# get a list containing the last 3 elements of a
last_a = a[-3:]

# reverse the list
reversed_a = a[::-1]

# get a list where each entry in a is cubed (so the new list is [1, 4, 9, 16, 25, 36])
cubed_a = [i ** 3 for i in a ]

In [378]:
# create a numpy array from this list
b = np.array(cubed_a) # change this
b

array([  1,   8,  27,  64, 125, 216])

In [379]:
# find the mean of b
b.mean()

73.5

In [380]:
# change b from a length-6 list to a 2x3 matrix
b = b.reshape(2,3)
b

array([[  1,   8,  27],
       [ 64, 125, 216]])

In [381]:
# find the mean value of each row
b.mean(axis=1)

array([ 12., 135.])

In [382]:
# find the mean value of each column
b.mean(axis=0)

array([ 32.5,  66.5, 121.5])

In [383]:
# find the third column of b
b[:,2]

array([ 27, 216])

In [384]:
# get a list where each entry in b is cubed (so the new numpy array is [1, 4, 9, 16, 25, 36])
# use a different (numpy-specific) approach
b = np.array(a)
b = np.power(b, 3)

In [385]:
# load in the "starbucks.csv" dataset
df = pd.read_csv("starbucks.csv")
df.head()
df

Beverage_category                                      Beverage  \
0                        Coffee                                 Brewed Coffee   
1                        Coffee                                 Brewed Coffee   
2                        Coffee                                 Brewed Coffee   
3                        Coffee                                 Brewed Coffee   
4       Classic Espresso Drinks                                   Caffè Latte   
..                          ...                                           ...   
237  Frappuccino® Blended Crème  Strawberries & Crème (Without Whipped Cream)   
238  Frappuccino® Blended Crème          Vanilla Bean (Without Whipped Cream)   
239  Frappuccino® Blended Crème          Vanilla Bean (Without Whipped Cream)   
240  Frappuccino® Blended Crème          Vanilla Bean (Without Whipped Cream)   
241  Frappuccino® Blended Crème          Vanilla Bean (Without Whipped Cream)   

          Beverage_prep  Calories  Total Fat (g)  Trans Fat (g)   \
0                 Short         3            0.1             0.0   
1                  Tall         4            0.1             0.0   
2                Grande         5            0.1             0.0   
3                 Venti         5            0.1             0.0   
4     Short Nonfat Milk        70            0.1             0.1   
..                  ...       ...            ...             ...   
237             Soymilk       320            3 2             0.4   
238    Tall Nonfat Milk       170            0.1             0.1   
239          Whole Milk       200            3.5             2.0   
240             Soymilk       180            1.5             0.2   
241  Grande Nonfat Milk       240            0.1             0.1   

     Saturated Fat (g)   Sodium (mg)   Total Carbohydrates (g)   \
0                  0.0             0                          5   
1                  0.0             0                         10   
2                  0.0             0                         10   
3                  0.0             0                         10   
4                  0.0             5                         75   
..                 ...           ...                        ...   
237                0.0             0                        250   
238                0.0             0                        160   
239                0.1            10                        160   
240                0.0             0                        160   
241                0.0             5                        230   

     Cholesterol (mg)   Dietary Fibre (g)   Sugars (g)   Protein (g)   \
0                   0                   0            0            0.3   
1                   0                   0            0            0.5   
2                   0                   0            0            1.0   
3                   0                   0            0            1.0   
4                  10                   0            9            6.0   
..                ...                 ...          ...            ...   
237                67                   1           64            5.0   
238                39                   0           38            4.0   
239                39                   0           38            3.0   
240                37                   1           35            3.0   
241                56                   0           55            5.0   

    Vitamin A (% DV)  Vitamin C (% DV)  Calcium (% DV)  Iron (% DV)   \
0                  0%               0%               0%           0%   
1                  0%               0%               0%           0%   
2                  0%               0%               0%           0%   
3                  0%               0%               2%           0%   
4                 10%               0%              20%           0%   
..                ...              ...              ...          ...   
237                6%               8%

In [386]:
# this is nutritional info for starbucks items
# let's see if we can answer some questions

# what is the average # calories across all items?
df["Calories"].mean()

193.87190082644628

In [387]:
# how many different categories of beverages are there?
len(df["Beverage"].unique())

33

In [388]:
# what is the average # calories for each beverage category?
bevs = df.groupby("Beverage")
bevs["Calories"].mean()

Beverage
Banana Chocolate Smoothie                              290.000000
Brewed Coffee                                            4.250000
Caffè Americano                                         13.750000
Caffè Latte                                            139.166667
Caffè Mocha (Without Whipped Cream)                    210.000000
Cappuccino                                              90.000000
Caramel                                                150.000000
Caramel (Without Whipped Cream)                        268.888889
Caramel Apple Spice (Without Whipped Cream)            247.500000
Caramel Macchiato                                      184.166667
Coffee                                                 210.000000
Espresso                                                 7.500000
Hot Chocolate (Without Whipped Cream)                  236.666667
Iced Brewed Coffee (With Classic Syrup)                 93.333333
Iced Brewed Coffee (With Milk & Classic Syrup)         122.222222
J

In [389]:
# what beverage preparation includes the most sugar?
df.groupby("Beverage_prep")[" Sugars (g)"].max().sort_values()

# Whole Milk! 

Beverage_prep
Doppio                 0
Solo                   0
Short Nonfat Milk     29
Short                 33
Tall Nonfat Milk      45
Tall                  49
Grande Nonfat Milk    62
Grande                65
2% Milk               74
Soymilk               80
Venti                 83
Venti Nonfat Milk     84
Whole Milk            84
Name:  Sugars (g), dtype: int64

In [390]:
# what is the average % daily value calcium content for each beverage?
# HINT: make sure your columns have the datatypes you want
# (you can use more than one line for this one)

df[" Calcium (% DV) "] = df[" Calcium (% DV) "].str.rstrip('%').astype(float)
df.groupby("Beverage")[" Calcium (% DV) "].mean()


Beverage
Banana Chocolate Smoothie                              20.000000
Brewed Coffee                                           0.500000
Caffè Americano                                         1.500000
Caffè Latte                                            35.000000
Caffè Mocha (Without Whipped Cream)                    30.000000
Cappuccino                                             22.500000
Caramel                                                11.000000
Caramel (Without Whipped Cream)                        12.000000
Caramel Apple Spice (Without Whipped Cream)             0.000000
Caramel Macchiato                                      28.333333
Coffee                                                 12.333333
Espresso                                                0.000000
Hot Chocolate (Without Whipped Cream)                  35.000000
Iced Brewed Coffee (With Classic Syrup)                 0.000000
Iced Brewed Coffee (With Milk & Classic Syrup)          8.000000
Java Chip       

In [391]:
# It's bulking season. What drink should Jackson get so that he maximizes protein but minimizes fat?
# (you can use more than one line for this one)

df.columns
df = df[df[' Total Fat (g)'].apply(lambda x : x.isnumeric())]

df[' Total Fat (g)'] = df[' Total Fat (g)'].astype(float)
df.groupby(['Beverage', 'Beverage_prep']).agg({' Total Fat (g)':'min', ' Protein (g) ':'max'}).sort_values(by=[' Protein (g) '], ascending=False)

protein_fat_ratio = df[' Protein (g) '].divide(df[' Total Fat (g)'], fill_value=0)
df['protein_fat_ratio'] = protein_fat_ratio

df.sort_values(by='protein_fat_ratio', ascending=False)[df['protein_fat_ratio'] != np.inf]

# Best ratio Orange Mango Banana Smoothie 

/home/corlaban/.local/lib/python3.6/site-packages/ipykernel_launcher.py:13: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  del sys.path[0]


Beverage_category                                    Beverage  \
175                  Smoothies                Orange Mango Banana Smoothie   
178                  Smoothies                  Strawberry Banana Smoothie   
71   Signature Espresso Drinks                           Caramel Macchiato   
68   Signature Espresso Drinks                           Caramel Macchiato   
179                  Smoothies                  Strawberry Banana Smoothie   
..                         ...                                         ...   
104           Tazo® Tea Drinks                                   Tazo® Tea   
105           Tazo® Tea Drinks                                   Tazo® Tea   
166      Shaken Iced Beverages  Shaken Iced Tazo® Tea (With Classic Syrup)   
167      Shaken Iced Beverages  Shaken Iced Tazo® Tea (With Classic Syrup)   
168      Shaken Iced Beverages  Shaken Iced Tazo® Tea (With Classic Syrup)   

          Beverage_prep  Calories   Total Fat (g)  Trans Fat (g)   \
175  Grande Nonfat Milk       260             1.0             0.3   
178  Grande Nonfat Milk       290             1.0             0.3   
71    Venti Nonfat Milk       240             1.0             1.0   
68   Grande Nonfat Milk       190             1.0             1.0   
179             2% Milk       290             2.0             1.0   
..                  ...       ...             ...             ...   
104              Grande         0             0.0             0.0   
105               Venti         0             0.0             0.0   
166                Tall        60             0.0             0.0   
167              Grande        80             0.0             0.0   
168               Venti       120             0.0             0.0   

     Saturated Fat (g)   Sodium (mg)   Total Carbohydrates (g)   \
175                0.0             5                        120   
178                0.0             5                        125   
71                 0.0            10                        170   
68                 0.0            10                        130   
179                0.0             5                        125   
..                 ...           ...                        ...   
104                0.0             0                          0   
105                0.0             0                          0   
166                0.0             0                          0   
167                0.0             0                          0   
168                0.0             0                          0   

     Cholesterol (mg)   Dietary Fibre (g)   Sugars (g)   Protein (g)   \
175                54                   6           37           16.0   
178                58                   7           41           16.0   
71                 43                   0           41           13.0   
68                 35                   0           32           11.0   
179                58                   7           41           16.0   
..                ...                 ...          ...            ...   
104                 0                   0            0            0.0   
105                 0                   0            0            0.0   
166                15                   0           15            0.0   
167                21                   0           21            0.0   
168                31                   0           31            0.0   

    Vitamin A (% DV)  Vitamin C (% DV)   Calcium (% DV)  Iron (% DV)   \
175               50%              80%              10.0          30%   
178                4%             100%              10.0           8%   
71                25%               0%              40.0           0%   
68                20%               0%              35.0           0%   
179                4%             100%              10.0           8%   
..                ...              ...               ...          ...   
104                0%               0%               0